### ISSUE TITLE
[FE] 외장 색상 컴포넌트 (360도) 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#106]
## ✨ Description

외장 색상 컴포넌트 (360도) 구현
<img width="741" alt="스크린샷 2023-08-08 오후 6 52 26" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/5b18df53-9550-49cf-85fb-4fc716fea7fc">

## ✅ Tasks

- [x] 차량 하단 360도 div 구현
- [x] 차량 이미지 받아오기
- [x] 차량 드래그 이벤트 설정
