### ISSUE TITLE
[FE] 내장 색상 컴포넌트

### ISSUE THREAD

**Issue by Hosung99** [softeerbootcamp-2nd/A5-Idle#107]
## ✨ Description
<img width="956" alt="image" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/84187086/3d882185-60c1-46c3-bb45-f86fa70d9d9b">

구현할 기능 설명
내장색상버튼을 누를 시 첫 아이템을 전역 차객체에 넣고 선택가능한 색상들을 띄운다.

## ✅ Tasks

- [x] 내장색상버튼 누를 시 화면 렌더링
- [x] 첫 아이템을 전역 차객체에 넣는다
- [x] 선택가능한 색상들을 띄운다.
