### ISSUE TITLE
[FE] 옵션 선택 메인 컴포넌트

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#110]
## ✨ Description

구현할 기능 설명

![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/9db4e2ea-0e1a-42b5-b81c-d7a68925832c)

## ✅ Tasks

- [x] data 받아오기
- [x] 옵션 렌더링
- [x] 해당 옵션에 속한 기능 렌더링
- [x] 좌우측 버튼 클릭 시 다음 옵션으로 이동
- [x] 하단에 몇 개의 옵션이 있는지, 몇 번째 옵션인지 표시
