### ISSUE TITLE
[FE] 기본 옵션 창 

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#111]
## ✨ Description

구현할 기능 설명
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/3d3ad358-7128-4ee1-af49-ac784752c7d3)

## ✅ Tasks

- [x] 기존에 만든 트림 찾기 모달 창 가져와서 height만 조절
- [x] tab component 재활용
- [x] 생성된 옵션 별 component 사용
- [x] 하단에 현재 페이지 표시
- [x] 좌우 버튼으로 페이지 이동
