### ISSUE TITLE
[FE] 옵션 박스 공용 컴포넌트 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#112]
## ✨ Description
옵션 박스 공용 컴포넌트 구현

<img width="828" alt="스크린샷 2023-08-09 오후 3 11 14" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/bdba6426-1a21-4337-a937-129aa33948d5">

## ✅ Tasks

- [x] 옵션 박스 css
- [x] prop으로 자기가 on/off를 boolean, 텍스트, 가격, 등등
- [x] 전역 차 객체에 따라 현재 자기 state 렌더링
- [x] 고민해보기,취소하기, 추가하기 버튼 컴포넌트 재사용
- [x] 각각 버튼에 prop으로 state주고, 온클릭 함수 주기
- [x] 추가하기 온클릭 → 전역 차 객체에 저장
- [x] 취소하기 온클릭 → 전역 차 객체에 삭제
- [x] 고민해보기 온클릭 → 전역 차 객체에 저장
