### ISSUE TITLE
[FE] 옵션 박스 컨테이너 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#114]
## ✨ Description
구현할 기능 설명
<img width="819" alt="스크린샷 2023-08-09 오후 3 17 54" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/315326c9-7f8a-4a3b-8eae-69b9d9615fe6">

## ✅ Tasks

- [x] 옵션 박스 컨테이너 css
- [x] 옵션 메인 페이지에 있는 selectedIdx에 따라 옵션박스을 렌더링
- [x] prop으로 isSelcted(boolean), 데이터
- [x] 스크롤 기능
- [x] 그리드 뷰에서 쓴 좌우 버튼
