### ISSUE TITLE
[BE] 9. 기본 옵션

### ISSUE THREAD

**Issue by Hypersand** [softeerbootcamp-2nd/A5-Idle#14]
## ✨ Description

기본 옵션 페이지 호출 API 구현 및 테스트 코드 작성

## ✅ Tasks

- [x] 기본 옵션 페이지 api 구현
- [x] 기본 옵션 페이지 테스트 코드 작성
- [x] 기능 목록 가나다순 정렬
