### ISSUE TITLE
[BE] 15. 견적서 정보

### ISSUE THREAD

**Issue by jeongyeonKimm** [softeerbootcamp-2nd/A5-Idle#145]
## ✨ Description

견적서 정보 반환

## ✅ Tasks

- [x] 외장 색상 이미지 반환
- [x] 내장 색상 이미지 반환
- [x] 추가 옵션 정보(카테고리, 이미지, 설명) 반환
