### ISSUE TITLE
[FE] 개발 환경 세팅

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#15]
## ✨ Description

React와 Styled Component를 적용하는 초기 환경 세팅

## ✅ Tasks

- [x] Vite를 통한 React 초기 세팅
- [x] React Router DOM 세팅
- [x] Styled-Component 세팅
- [x] prettier 설정
