### ISSUE TITLE
[FE] 페이지 전환 애니메이션 추가

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#150]
## ✨ Description

페이지 전환 애니메이션 추가

## ✅ Tasks

- [ ] 라이브러리 사용하지 않고 애니메이션 추가 방법 알아보기
- [ ] opacity 부터 적용해보기
- [ ] 할 수 있다면 좌우로 넘어가기도 구현 시도
