### ISSUE TITLE
[BE] 내게 맞는 트림 찾기 API Test 수정

### ISSUE THREAD

**Issue by sue06004** [softeerbootcamp-2nd/A5-Idle#152]
## ✨ Description

내게 맞는 트림 찾기 API의 테스트 코드를 단위 테스트로 리팩토링

## ✅ Tasks
- [ ] MyTrimControllerTest 단위 테스트로 리팩토링
- [ ] MyTrimServiceTest 단위 테스트로 리팩토링
- [ ] FunctionRepositoryImpleTest 단위 테스트로 리팩토링
