### ISSUE TITLE
[FE] 트림 메인 페이지 

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#16]
## ✨ Description

최초 페이지 트림 선택 페이지 구현

## ✅ Tasks

- [x] 백엔드 데이터 통신
- [x] 공용 컴포넌트 재사용
- [x] 전체 틀 css
- [x] 페이지 Router 적용
- [x] 트림별 이미지 저장
- [x] 전역 차 객체에 따른 이미지 렌더
