### ISSUE TITLE
[FE] 내게맞는 트림찾기 API연결

### ISSUE THREAD

**Issue by Hosung99** [softeerbootcamp-2nd/A5-Idle#171]
## ✨ Description

내게맞는 트림찾기에 백엔드 API연결하려고합니다.

## ✅ Tasks

- [x] 내게 맞는 트림 찾기에서 선택지 선택시 호출할 API
- [x] 내게 맞는 트림 찾기에서 트림 선택시 호출할 API
- [x] 내게 맞는 트림 찾기에서 확인 버튼을 눌렀을 때 호출할 API
