### ISSUE TITLE
[hotfix] RequestBody -> QueryString으로 변경

### ISSUE THREAD

**Issue by Hypersand** [softeerbootcamp-2nd/A5-Idle#178]
## ✨ Description
GET 요청 시 RequestBody로 넘기던 데이터 QueryString으로 변경

## ✅ Tasks
- [x] 세부 모델 선택 페이지 호출 API
- [x] 기본 옵션 페이지 호출 API
- [x] 견적서 정보 호출 API
