### ISSUE TITLE
[FE] 일반 버튼 컴포넌트 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#18]
## ✨ Description

파란색 (다음), 흰색 ( 나가기 ) 버튼 컴포넌트 구현

<img width="300" alt="스크린샷 2023-08-01 오후 11 40 54" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/06da78a9-e96b-4aca-8182-46ef9dd407f5">

## ✅ Tasks

- [x] 각 버튼 css
- [x] 버튼 비활성화 버전 css
- [x] prop ( 버튼 텍스트, 활성화 상태, 온클릭 이벤트 함수 ) 설정
- [x] prop에 버튼 연결
