### ISSUE TITLE
[BE] 내게 맞는 트림 찾기 POST로 수정

### ISSUE THREAD

**Issue by sue06004** [softeerbootcamp-2nd/A5-Idle#184]
## ✨ Description
내게 맞는 트림 찾기의 선택지 선택시와 확인 버튼 눌렀을 때 API post로 변경

## ✅ Tasks

- [x] 선택지 선택시 API POST로 변경
- [x] 확인 버튼 API POST로 변경
- [x] test코드 post로 변경
