### ISSUE TITLE
[BE] 세부모델 선택 가격 오름차순 정렬

### ISSUE THREAD

**Issue by Hypersand** [softeerbootcamp-2nd/A5-Idle#187]
## ✨ Description

엔진, 구동방식, 바디 타입 가격 오름차순으로 정렬

## ✅ Tasks

- [x] 엔진 목록 가격 오름차순으로 정렬
- [x] 바디타입 목록 가격 오름차순으로 정렬
- [x] 구동방식 목록 가격 오름차순으로 정렬
