### ISSUE TITLE
[FE] 툴팁 공용 컴포넌트 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#19]
## ✨ Description

내게 맞는 트림 찾기, 카테고리 툴팁 + 고민해보기 툴팁  컴포넌트 구현

<img width="300" alt="스크린샷 2023-08-01 오후 11 37 31" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/9b9c33fb-3b59-4d65-9f7d-9856169a6682">

## ✅ Tasks

- [x] 내게 맞는 트림 찾기 + 카테고리 용 툴팁 css
- [x] 고민해보기 툴팁 css
- [x] Prop ( 툴팁 내용, 활성화 상태 ) 설정
- [x] 툴팁 클릭시 툴팁 off ( 추가 기능 )
