### ISSUE TITLE
[FE] 경고 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#20]
## ✨ Description

경고 모달 컴포넌트 구현

<img width="400" alt="스크린샷 2023-08-02 오전 10 14 46" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/7ab8e0b2-8687-4d7c-8237-ad04fe217b53">

## ✅ Tasks
- [x] 모달 css
- [x] 취소, 확인버튼 일반 버튼 컴포넌트 재사용
- [x] 각 버튼의 온클릭 함수 prop 전달
- [x] 모달 내용 prop 받기
- [x] 확인 버튼 누를 시 라우팅
