### ISSUE TITLE
[FE] 진행 우측 네비게이션 창 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#22]
## ✨ Description

우측 진행 내비게이션 창 구현
(트림, 세부모델, 색상, 옵션, 완성)

<img width="298" alt="스크린샷 2023-08-02 오전 10 19 01" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/1526c310-efd6-40fb-ab7f-16aacdcb97be">

## ✅ Tasks

- [x] 진행상황 네비게이션 창 css
- [x] 예상 가격 css
- [x] 체크 로고 svg init
- [x] getState로 현재 진행중인 창 focus 효과
- [x] 각 진행박스 클릭시에 해당 창으로 이동 ( setState로 현재 진행 state 바꾸기 )
- [x] 옵션 박스에서 3개 이상일때 …외 n개 로 출력
- [x] 전역 차 객체에 저장되어 있는 항목들 업데이트
- [x] 각 박스 옵션들의 가격 합 업데이트
- [x] 전역 차 객체에 들어간 옵션 가격 총합 업데이트
