### ISSUE TITLE
[FE] 옵션 포함 상태에서 트림 변경시 경고 모달 출력

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#221]
## ✨ Description

옵션 포함 상태에서 트림 변경시 경고 모달 출력

<img width="618" alt="스크린샷 2023-08-16 오후 5 55 30" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/9376e6f5-c92e-4ea5-afb8-a9d6a74b0735">

## ✅ Tasks

- [x] reducer 수정
- [x] 경고 모달 재사용을 위한 수정
- [x] 경고 모달 사용중인 로고 컴포넌트 수정
- [x] 중간 디테일 멘트 prop 추가
