### ISSUE TITLE
[FE] 모든 옵션들을 선택했을 때 견적서 이동이 가능하도록 변경

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#230]
## ✨ Description

모든 옵션들을 선택했을 때 견적서 이동이 가능하도록 변경

## ✅ Tasks

- [x] 경고 모달에 연결
- [x] 추가 기능으로 필요한 옵션 탭으로 navigate
- [x] 다음 버튼으로 이동 할때에도 체크
