### ISSUE TITLE
[BE] CarMaster API 수정

### ISSUE THREAD

**Issue by sue06004** [softeerbootcamp-2nd/A5-Idle#232]
## ✨ Description
CarMaster API의 주소도 같이 반환하도록 변경

## ✅ Tasks
- [x] CarMaster img url 정보 추가
- [x] marker image url 추가
- [x] 주소, 마커 url 반환
