### ISSUE TITLE
[BE] CarMaster data 추가

### ISSUE THREAD

**Issue by sue06004** [softeerbootcamp-2nd/A5-Idle#235]
## ✨ Description
data.sql 수정

## ✅ Tasks

- [x] data.sql에 img_url 컬럼에 값 추가
- [x] data.sql에 marker_img_url 컬럼 및 데이터 추가
- [x] data.sql에 address 컬럼 추가 및 데이터 추가
