### ISSUE TITLE
[FE] 자동차 모델명 클릭

### ISSUE THREAD

**Issue by Hosung99** [softeerbootcamp-2nd/A5-Idle#24]
## ✨ Description

구현할 기능 설명
<img width="300" alt="image" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/84187086/29fa5560-6e7d-4a37-b803-e5ad6b921186">

## ✅ Tasks

- [ ] 모델명 텍스트 css
- [ ] 아래 내리기 버튼 로고 가져오기
- [ ] 버튼 누를 시에 자동차 모델 리스트 출력
- [ ] 올라가기 버튼 누를 시에 리스트 접기
- [ ] 각 차량의 리스트는 클릭 막기
