### ISSUE TITLE
[FE] 트림이미지 기능 좌표 설정

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#241]
## ✨ Description

트림이미지 기능 좌표 설정

<img width="475" alt="스크린샷 2023-08-17 오후 1 03 15" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/abe96acc-fa79-48e6-9e6c-522e08fb5177">

## ✅ Tasks

- [x] api상 트림 기능 좌표 데이터 받아오기
- [x] 픽셀 좌표에 기능 위치 표시하는 디자인 추가
- [x] 호버나 클릭시 기능 팝업
