### ISSUE TITLE
[FE] 트림 박스 컨테이너

### ISSUE THREAD

**Issue by Hosung99** [softeerbootcamp-2nd/A5-Idle#25]
## ✨ Description

구현할 기능 설명
<img width="810" alt="image" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/84187086/d6a1517d-2340-4a13-8fa8-82c16db4e54b">
H 트림 박스 컨테이너

## ✅ Tasks

- [x] 받아온 트림 리스트로 트림박스 생성
- [x] 기본 상태 0번째 트림박스 true 로 설정
- [x] 각 트림박스에 대한 클릭 이벤트 함수 전달
- [x] 클릭 이벤트 함수 - 차 객체에 옵션이 있는지 확인하는 함수로 체크 + 더듬이 이미지 변경
- [ ] 있다면 경고모달 컴포넌트 출력
- [ ] 없다면 차 객체에 트림 업데이트
