### ISSUE TITLE
[FE] 트림 페이지 자세히 보기 기능 선택 시 모달 창

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#258]
## ✨ Description

구현할 기능 설명
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/8833b079-e5af-4946-8655-bdb765b2adcc)
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/8a3760a3-0dc5-4c8d-aff0-566c5513a29e)

## ✅ Tasks

- [ ] 트림 박스마다 트림 id 데이터 입력
- [ ] 자세히 보기 클릭시 기본옵션 api 호출
- [ ] 클릭 시 해당 옵션 모달 창 띄우기
