### ISSUE TITLE
[FE] 노말 트림 박스 컴포넌트 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#26]
## ✨ Description

트림에 대한 정보를 담은 박스 컴포넌트 구현

<img width="1068" alt="스크린샷 2023-08-02 오전 10 35 18" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/43f45aed-f6f5-49d6-93ec-1d4b2d7d573d">

## ✅ Tasks

- [x] 박스 선택 버전 css
- [x] 박스 일반 버전 css
- [x] 표시할 데이터 prop 설정  - (구매자 비율, 트림 이름, 트림 설명, 가격, 선택 여부 )
- [ ] 자세히 보기 버튼 구현
- [ ] 자세히 보기 버튼 클릭 이벤트 함수 -> prop으로 받은 트림 이름을 자세히보기 모달에 전달
