### ISSUE TITLE
[FE] 내게 맞는 트림 찾기 모달 창 구현

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#27]
## ✨ Description

구현할 기능 설명
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/643a01ec-25f0-48fc-9438-4ad8949f3143)
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/55b189a0-110e-4d9a-93f4-c5bd92abacc3)
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/e97661e9-de28-4afc-9385-fe0e16d4ef2c)

(안에 트림 박스, 기능 박스는 구현 X  Only 전체 구조만)

## ✅ Tasks

- [x] 내게 맞는 트림 찾기 버튼 css
- [x] 전체 모달 창 구현 및 css
- [x] 버튼 클릭 시 모달이 올라오고, 원하는 기능~~~~로 텍스트 변경
- [x] 확인 버튼을 누를 때 트림이 변경되었는지 체크 후
- [x] 변경되었다면 경고 모달 띄우기, 변경X 시 전체 차 객체에 반영
