### ISSUE TITLE
[BE] CAR_TYPE, CAR_CATEGORY 추가

### ISSUE THREAD

**Issue by sue06004** [softeerbootcamp-2nd/A5-Idle#274]
## ✨ Description
data.sql과 schema.sql에 car_category테이블 추가 및 car_type테이블 수정, 데이터 추가

## ✅ Tasks
- [x] schema.sql에 car_category테이블 추가, car_type테이블 수정
- [x] data.sql에 car_category, car_typ테이블에 들어갈 데이터 추가
- [x] s3에 차종별 사진, 로고 사진 추가
