### ISSUE TITLE
[FE] 차량 선택 페이지 만들기

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#280]
## ✨ Description

구현할 기능 설명
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/6aad6090-c489-4593-b21c-24878df720b4)

## ✅ Tasks

- [x] 박스 컴포넌트 만들기
- [x] api로 데이터 받아오기 
- [x] tab 재활용
- [x] 아래 페이지네이션 및 버튼 생성
- [x] 메인 페이지 카마스터 시작하기 navigate 수정
