### ISSUE TITLE
[FE] 이미지 최적화 시도

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#296]
## ✨ Description

이미지 최적화 시도

## ✅ Tasks

- [x] 이미지 프리로딩 시도
- [x] 이미지 데이터 context 저장 시도
- [ ] 데이터 api 통신 최소화 시도
