### ISSUE TITLE
[BE] carType API 요구사항에 맞게 수정

### ISSUE THREAD

**Issue by sue06004** [softeerbootcamp-2nd/A5-Idle#303]
## ✨ Description
isNew 추가
가격 단위 만원 단위로 변경

## ✅ Tasks
- [x] carType데이터에 isNew 데이터 추가
- [x] 반환 데이터에 isNew추가
- [x] 가격 단위 만원 단위로 변경
