### ISSUE TITLE
[BE] 추가 옵션 및 견적서 페이지 POST -> GET 요청으로 변경

### ISSUE THREAD

**Issue by Hypersand** [softeerbootcamp-2nd/A5-Idle#309]
## ✨ Description
추가 옵션 및 견적서 페이지 Request Body에 담아서 POST로 보내던 요청 QueryString + GET 요청으로 변경

## ✅ Tasks
- [ ] 추가 옵션 선택 페이지 GET 요청 및 Query String으로 변경
- [ ] 견적서 페이지 GET 요청 및 Query String으로 변경
- [ ] 테스트 코드 수정
