### ISSUE TITLE
[BE] DB에 구매 비율 int로 저장

### ISSUE THREAD

**Issue by sue06004** [softeerbootcamp-2nd/A5-Idle#349]
## ✨ Description
DB에 구매 비율 int로 저장하도록 변경

## ✅ Tasks
- [x] schema.sql에 purchase_rate 타입 int로 변경
- [x] h2Schema.sq 변경
- [x] data.sql에 purchase_rate을 null insert후 판매 데이터를 통해 업데이트하도록 변경
- [x] ec2 mysql에도 적용
