### ISSUE TITLE
[FE] 초기 진입 페이지 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#45]
## ✨ Description

초기 진입 페이지 구현

## ✅ Tasks

- [x] 영상 파일 추가
- [x] 현대차 로고 컴포넌트 재사용
- [x] 마이 카마스터 시작하기 버튼 구현
- [x] 초기 진입 페이지 라우터 설정
- [x] 페이지 전체 css
