### ISSUE TITLE
[FE] 내게 맞는 트림 찾기 내 기능 박스 컴포넌트 & 컨테이너 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#47]
## ✨ Description

내게 맞는 트림 찾기 내 기능 박스 & 컨테이너 컴포넌트 구현
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/64088f1f-aeae-44dc-a1cc-a91ada7ace9a)

![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/3ef9a5e3-7a21-4649-a2f1-f398103c5488)

## ✅ Tasks

- [x] 기능 박스 css
- [x] prop으로 ( 텍스트, 상세보기에 들어갈 데이터(이미지나 뭐 설명), 온클릭 함수)
- [x] 박스의 on/off
- [x] - 받아온 데이터상의 기능 리스트는 map으로 9개 기능 박스 생성
- [x] 전해줄 인자는 → 텍스트, 상세보기 데이터
- [x] 상세보기 버튼 온클릭 함수( 클릭시 디테일 모달창 띄우기)
