### ISSUE TITLE
[FE] 상세 옵션 정보 모달창 컴포넌트

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#56]
## ✨ Description
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/7d70235d-63ec-4cd6-b60a-92801d59cccc)

## ✅ Tasks
- [x] - 상세 옵션 정보 모달창 css
- [x]  prop 으로 해당 옵션에 대한 데이터 받기
- [x] 선택하기 버튼은 다음버튼 공용 컴포넌트 재사용 - 무조건 활성화
- [x] 온클릭 함수는 → prop에서 받은 옵션을 selectedoption context에 추가
- [ ] X 버튼 공용컴포넌트 재사용 - 온클릭 함수 → 상세옵션 정보 모달 창 닫기

**Comment by jjun990908** [comment]
이거 생각해보니까 트림 자세히보기 옵션에서 띄울 모달창 컴포넌트가 이거인데
그때는 아래 선택하기가 없어야해서, 재사용하려면 상태 나눠야할듯합니다
