### ISSUE TITLE
[FE] 트림 자세히 보기 팝업 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#57]
## ✨ Description

트림 자세히 보기 팝업 구현

## ✅ Tasks

- [x] 드롭다운 메뉴 컴포넌트 만들기
- [x] 버튼 컴포넌트 재사용 - 온클릭→ 모달창 끄기
- [x] 일반 트림박스 자세히 보기 버튼 수정
- [x] api 명세서에 따른 더미 데이터 연결
- [x] 드롭다운 기능 구현
- [x] 드롭다운 애니메이션 구현
- [x] 모달 창 뒷 배경 흐림 효과 추가
- [ ] 드롭다운 후 기능 추가 설명 모달 창 구현
