### ISSUE TITLE
[BE] 3. 세부 모델 선택

### ISSUE THREAD

**Issue by Hypersand** [softeerbootcamp-2nd/A5-Idle#6]
## ✨ Description
세부 모델(엔진, 구동 방식, 바디 타입) 선택 페이지

## ✅ Tasks
- [x] 엔진 선택
- [x] 구동 방식 선택
- [x]  바디 타입 선택
- [x] 테스트 코드 작성

**Comment by jeongyeonKimm** [comment]
세부 모델 선택 구현 완료
