### ISSUE TITLE
[FE] 확인 버튼 ( 내게 맞는 트림 찾기 ) - 활성/비활

### ISSUE THREAD

**Issue by Hosung99** [softeerbootcamp-2nd/A5-Idle#65]
## ✨ Description

내게맞는 트림찾기에서 확인 버튼이 처음엔 비활성화 되어있는데,
트림을 선택시에 이를 활성화 하고 아래 기능 수행하기

## ✅ Tasks

- [x] 트림선택시에 확인버튼을 활성화하기 (모달에서 새로 만들어진 차 객체.트림이름 ≠ null ? 활성 : 비활성)
- [x] 확인버튼 온클릭함수 → 모달에서 만든 차 객체를 전역 차 객체로 덮어씌우기
- [x] 확인버튼 온클릭함수 → 모달 끄기 
- [x] 확인버튼 온클릭함수 → 모달 차 객체 옵션을 옵션 추가 알림 alert 컴포넌트에 전달
