### ISSUE TITLE
[FE] 옵션 변경시 데이터 변경과 경고 모달

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#66]
## ✨ Description

구현할 기능 설명
![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/9c8e036a-57b2-4d10-9e0b-6f8eab22e9ca)

## ✅ Tasks

- [x] 모달 css
- [x] prop으로 옵션 데이터 받아오기
- [x] 취소, 확인 컴포넌트 재사용
- [x] 취소 온클릭 → 모달 닫기
- [x] 확인 온클릭 → prop을 전역 차 객체에 업데이트 & 모달 닫기
