### ISSUE TITLE
[FE] 카테고리 탭 컴포넌트 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#67]
## ✨ Description

카테고리 탭 컴포넌트 구현

## ✅ Tasks

- [x] 텍스트와 on/off 상태별 css
- [x] prop으로 텍스트, 온클릭함수
- [x] 데이터 받아서 foreach나 map 으로 상세모델 선택목록 컴포넌트 재사용

## 구현 목표 이미지
<img width="233" alt="스크린샷 2023-08-07 오전 11 22 03" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/2abe9da0-dfd8-46dd-888a-31fb965fa249">
