### ISSUE TITLE
[FE] 엔진 데이터 컴포넌트 구현

### ISSUE THREAD

**Issue by jjun990908** [softeerbootcamp-2nd/A5-Idle#68]
## ✨ Description

엔진 데이터 컴포넌트 구현

## ✅ Tasks

- [x] 이미지 및 컴포넌트 css
- [x] prop으로 엔진 이미지, 출력, 토크, 연비 데이터
- [x] 각 데이터별로 차트 구현

## 구현 목표 이미지
<img width="923" alt="스크린샷 2023-08-07 오전 11 25 39" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/39405559/53d58642-ea34-4c0b-9296-a1355ee87bd1">
