### ISSUE TITLE
[FE] 상세 옵션 정보 모달창

### ISSUE THREAD

**Issue by Hosung99** [softeerbootcamp-2nd/A5-Idle#69]
## ✨ Description

내게 맞는 트림찾기에서 옵션에 있는 상세보기를 누를시 나타나는 모달창 구현

## ✅ Tasks

- [ ] 상세 옵션 정보 모달창 css
- [ ] prop 으로 해당 옵션에 대한 데이터 받기
- [ ] 선택하기 버튼은 다음버튼 공용 컴포넌트 재사용 - 무조건 활성화
- [ ] 온클릭 함수는 → prop에서 받은 옵션을 모달 차 객체에 추가 (중복 체크)
- [ ] X 버튼 공용컴포넌트 재사용 - 온클릭 함수 → 상세옵션 정보 모달 창 닫기

## 구현 목표 이미지

<img width="380" alt="image" src="https://github.com/softeerbootcamp-2nd/A5-Idle/assets/84187086/6c077e85-eed5-4a5a-9228-6a519251b93f">
