### ISSUE TITLE
[FE] 세부모델 박스 컴포넌트 & 컨테이너

### ISSUE THREAD

**Issue by Wongilk** [softeerbootcamp-2nd/A5-Idle#70]
## ✨ Description

![image](https://github.com/softeerbootcamp-2nd/A5-Idle/assets/108254103/3e7fbe54-5b71-492f-9eb1-4eca6ac0a8eb)

## ✅ Tasks
- [x]  박스 css
- [x] prop로 텍스트, 세부 내용, 가격
- [x]  on/off 상태는 전역 차 객체의 값에 따라 변경
- [x] 세부모델 박스 컴포넌트 재사용
- [x] 데이터 api 명세서 수정
- [x] 엔진, 구동방식, 바디타입 탭 state 설정
- [x] state별 렌더링 수정
