### ISSUE TITLE
[BE] 12. 내게 맞는 트림 찾기에서 확인 버튼 클릭시 호출 API

### ISSUE THREAD

**Issue by jeongyeonKimm** [softeerbootcamp-2nd/A5-Idle#85]
## ✨ Description

내게 맞는 트림 찾기에서 확인 버튼 클릭시 호출할 API

## ✅ Tasks
- [x] 선택된 기능에 대한 옵션정보를 반환
- [x]  테스트 코드 작성
- [x]  RequestBody의 trimId에 해당하는 트림에 functionId에 해당하는 기능이 존재하지 않으면 예외처리
