### ISSUE TITLE
[BE] application.yml 세팅

### ISSUE THREAD

**Issue by Hypersand** [softeerbootcamp-2nd/A5-Idle#99]
## ✨ Description

application.yml 세팅하기

## ✅ Tasks
- [x] application.yml test, dev, prod 분리 세팅
- [x] 환경 변수 Github Secrets으로 관리
- [x] dev 및 test 환경에서 schema.sql 및 data.sql을 통해 더미 데이터 생성

**Comment by jeongyeonKimm** [comment]
application.yml 세팅 완료
